// <auto-generated />
using System;
using ApliVentas.BD.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApliVentas.BD.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApliVentas.BD.Data.Entity.Ganancia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("fecha")
                        .HasMaxLength(8)
                        .HasColumnType("datetime2");

                    b.Property<int>("porcentajeGanancia")
                        .HasColumnType("int");

                    b.Property<int>("precio")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Ganancias");
                });

            modelBuilder.Entity("ApliVentas.BD.Data.Entity.PrecioFinal", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("Productoid")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("precioFinal")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Productoid");

                    b.ToTable("precioFinals");
                });

            modelBuilder.Entity("ApliVentas.BD.Data.Entity.Producto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("PrecioFinalid")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("precioProducto")
                        .HasMaxLength(40)
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("PrecioFinalid");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("ApliVentas.BD.Data.Entity.PrecioFinal", b =>
                {
                    b.HasOne("ApliVentas.BD.Data.Entity.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("Productoid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("ApliVentas.BD.Data.Entity.Producto", b =>
                {
                    b.HasOne("ApliVentas.BD.Data.Entity.PrecioFinal", null)
                        .WithMany("ProductoList")
                        .HasForeignKey("PrecioFinalid");
                });

            modelBuilder.Entity("ApliVentas.BD.Data.Entity.PrecioFinal", b =>
                {
                    b.Navigation("ProductoList");
                });
#pragma warning restore 612, 618
        }
    }
}
